name: Build Skin
on: workflow_dispatch
jobs:
  generatename:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Generate Release Name
        id: create_name
        run: |
          echo "::set-env name=TAG_NAME::$(npm run createname --silent)"
        
      - name: test
        run: echo "::debug::$(npm run createname --silent)"
  mktag:
    needs: generatename
    
    runs-on: [ubuntu-latest]
    
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      web_url: ${{ steps.create_release.outputs.html_url }}
    
    permissions: write-all
    
    steps:
      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
      
  publish:
    needs: [mktag, generatename]
  
    runs-on: [ubuntu-latest]
    
    permissions: write-all
    
    steps:
      - name: Check out Git Repo
        uses: actions/checkout@master
        
        
      - name: Install Node.js, and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 16
          
      - run: npm install
      
      - name: Build Skin
        run: npm run --silent build
        
      - name: Upload Skin to Github Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.mktag.outputs.upload_url }}
          asset_path: ./dist/skin.osk
          asset_name: seeds_skin-${{ env.TAG_NAME }}.osk
          asset_content_type: application/octet-stream